import React, { useState, useEffect } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import {
  ArrowLeft,
  FileText,
  TrendingUp,
  Target,
  Award,
  Book,
  Globe,
  Lightbulb,
  Download,
  BarChart3,
  Brain,
  Rocket,
  Clock,
  AlertCircle,
} from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useStudentAuth } from "@/contexts/StudentAuthContext";
import { useToast } from "@/hooks/use-toast";
import {
  getCachedAnalysisResults,
  analyzeStudentProfile,
  AdvisoryReport as AdvisoryReportType,
} from "@/services/studentAnalysisService";
import ConsultationModal from "@/components/ConsultationModal";

const AdvisoryReport = () => {
  const navigate = useNavigate();
  const { student } = useStudentAuth();
  const { toast } = useToast();
  const [advisoryData, setAdvisoryData] = useState<AdvisoryReportType | null>(
    null,
  );
  const [loading, setLoading] = useState(true);
  const [showConsultationModal, setShowConsultationModal] = useState(false);

  useEffect(() => {
    if (student) {
      loadAdvisoryReport();
    }
  }, [student]);

  const loadAdvisoryReport = async () => {
    try {
      console.log("Loading advisory report for student:", student.id);

      // Try to get cached analysis results first
      const cachedResults = await getCachedAnalysisResults(student.id);
      if (cachedResults?.advisory_report) {
        console.log("Using cached advisory report");
        setAdvisoryData(cachedResults.advisory_report);
        setLoading(false);
        return;
      }

      // Generate new analysis if no cached data
      console.log("Generating new advisory report...");
      const analysisResult = await analyzeStudentProfile(student.id);

      if (analysisResult.advisory_report) {
        setAdvisoryData(analysisResult.advisory_report);
        toast({
          title: "Advisory Report Generated! 📊",
          description: "Your personalized career roadmap is ready.",
        });
      } else {
        throw new Error("No advisory report generated");
      }
    } catch (error) {
      console.error("Failed to load advisory report:", error);
      toast({
        title: "Error Loading Report",
        description: `Failed to load your advisory report: ${error.message}. Please try again.`,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!advisoryData) return;

    // Create a simple text version of the report for download
    const reportContent = `
ZANE AI CAREER ADVISORY REPORT
Generated for: ${student?.full_name}
Date: ${new Date().toLocaleDateString()}

=== CAREER FIT ANALYSIS ===
Overall Score: ${advisoryData.career_fit.score}%

Next Actions:
${advisoryData.career_fit.next_actions.map((action, index) => `${index + 1}. ${action}`).join("\n")}

=== LEARNING PRIORITIES ===
${advisoryData.learning_priorities
  .map(
    (priority, index) => `
${index + 1}. ${priority.title}
   Priority: ${priority.priority}
   Timeframe: ${priority.timeframe}
   Next Action: ${priority.next_action}
`,
  )
  .join("\n")}

=== PATH STRATEGY ===
${advisoryData.path_strategy
  .map(
    (strategy, index) => `
${index + 1}. ${strategy.title}
   Priority: ${strategy.priority}
   Timeframe: ${strategy.timeframe}
   Next Action: ${strategy.next_action}
`,
  )
  .join("\n")}

---
Generated by Zane AI - ZaneProEd Career Intelligence Platform
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `zane-advisory-report-${student?.username || "student"}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Report Downloaded",
      description: "Your advisory report has been saved to your device.",
    });
  };

  if (loading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="text-center space-y-6">
          <div className="relative">
            <Brain className="w-16 h-16 animate-pulse text-navy-600 mx-auto mb-4" />
            <FileText className="w-8 h-8 text-autumn-500 absolute top-0 right-1/2 transform translate-x-8 animate-bounce" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-navy-800 mb-2">
              Generating Advisory Report
            </h2>
            <p className="text-lg text-slate-600 mb-4">
              Creating your personalized career roadmap...
            </p>
            <div className="max-w-md mx-auto">
              <Progress value={85} className="h-3 bg-slate-100" />
              <p className="text-sm text-slate-500 mt-2">
                This may take a few moments
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!advisoryData) {
    return (
      <div className="container mx-auto px-4 py-8">
        <Card>
          <CardContent className="text-center py-8">
            <AlertCircle className="w-12 h-12 text-slate-400 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-slate-600 mb-2">
              No Advisory Report Available
            </h3>
            <p className="text-muted-foreground mb-4">
              Please complete your profile analysis first to generate an
              advisory report.
            </p>
            <Button
              onClick={() => navigate("/analysis")}
              className="bg-gradient-to-r from-navy-600 to-autumn-500 text-white"
            >
              Go to Analysis
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  const getPriorityColor = (priority: string) => {
    switch (priority.toLowerCase()) {
      case "high":
        return "bg-red-100 text-red-800 border-red-300";
      case "medium":
        return "bg-yellow-100 text-yellow-800 border-yellow-300";
      case "low":
        return "bg-green-100 text-green-800 border-green-300";
      default:
        return "bg-gray-100 text-gray-800 border-gray-300";
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50">
      {/* Header */}
      <header className="border-b border-slate-200 bg-white/80 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4 flex justify-between items-center">
          <Link
            to="/analysis"
            className="flex items-center space-x-2 text-navy-600 hover:text-navy-700 transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>Back to Analysis</span>
          </Link>
          <div className="flex items-center space-x-3">
            <div className="w-8 h-8 bg-gradient-to-r from-navy-600 to-autumn-500 rounded-lg flex items-center justify-center">
              <Brain className="w-5 h-5 text-white" />
            </div>
            <div>
              <span className="text-navy-700 font-bold text-lg">Zane AI</span>
              <p className="text-slate-500 text-xs">by ZaneProEd</p>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8 space-y-8">
        {/* Report Header */}
        <div className="text-center space-y-4">
          <div className="inline-flex items-center px-6 py-3 bg-navy-100 text-navy-700 rounded-full text-sm font-medium">
            <FileText className="w-5 h-5 mr-2" />
            Career Advisory Report
          </div>
          <h1 className="text-3xl font-bold text-navy-800">
            Your Personalized Career Roadmap
          </h1>
          <p className="text-slate-600 max-w-2xl mx-auto">
            Based on comprehensive analysis of your profile, here's your
            detailed action plan for career success.
          </p>
          <div className="flex justify-center space-x-3">
            <Button
              onClick={handleDownloadReport}
              variant="outline"
              className="bg-white"
            >
              <Download className="mr-2 h-4 w-4" />
              Download Report
            </Button>
            <Button
              onClick={() => setShowConsultationModal(true)}
              className="bg-gradient-to-r from-navy-600 to-autumn-500 hover:from-navy-700 hover:to-autumn-600 text-white"
            >
              <Globe className="mr-2 h-4 w-4" />
              Book Consultation
            </Button>
          </div>
        </div>

        {/* Career Fit Score */}
        <Card className="bg-gradient-to-r from-navy-50 to-autumn-50 border-navy-200">
          <CardHeader>
            <CardTitle className="flex items-center text-navy-800">
              <BarChart3 className="mr-3 h-6 w-6" />
              Career Fit Analysis
            </CardTitle>
            <CardDescription>
              Overall assessment of your career readiness
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              <div>
                <div className="flex justify-between items-center mb-3">
                  <span className="text-lg font-semibold text-navy-700">
                    Overall Career Readiness
                  </span>
                  <span className="text-2xl font-bold text-navy-800">
                    {advisoryData.career_fit.score}%
                  </span>
                </div>
                <Progress
                  value={advisoryData.career_fit.score}
                  className="h-4 bg-white"
                />
                <p className="text-sm text-slate-600 mt-2">
                  {advisoryData.career_fit.score >= 80
                    ? "Excellent! You're well-prepared for your target roles."
                    : advisoryData.career_fit.score >= 60
                      ? "Good foundation with room for strategic improvements."
                      : "Focus on skill development to strengthen your profile."}
                </p>
              </div>

              <div>
                <h4 className="font-semibold text-navy-700 mb-3">
                  Immediate Next Actions
                </h4>
                <div className="space-y-2">
                  {advisoryData.career_fit.next_actions.map((action, index) => (
                    <div key={index} className="flex items-start space-x-2">
                      <Target className="w-4 h-4 mt-1 text-navy-600 flex-shrink-0" />
                      <span className="text-sm text-slate-700">{action}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Learning Priorities */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <Book className="mr-3 h-6 w-6 text-navy-600" />
              Learning Priorities
            </CardTitle>
            <CardDescription>
              Skills and knowledge areas to focus on for career advancement
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {advisoryData.learning_priorities.map((priority, index) => (
                <div
                  key={index}
                  className="p-4 border border-slate-200 rounded-lg"
                >
                  <div className="flex items-start justify-between mb-3">
                    <h4 className="font-semibold text-slate-800">
                      {priority.title}
                    </h4>
                    <div className="flex items-center space-x-2">
                      <Badge
                        variant="outline"
                        className={getPriorityColor(priority.priority)}
                      >
                        {priority.priority} Priority
                      </Badge>
                      <Badge
                        variant="outline"
                        className="bg-blue-100 text-blue-800 border-blue-300"
                      >
                        <Clock className="w-3 h-3 mr-1" />
                        {priority.timeframe}
                      </Badge>
                    </div>
                  </div>
                  <p className="text-sm text-slate-600 mb-2">
                    <strong>Next Action:</strong> {priority.next_action}
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Path Strategy */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <Rocket className="mr-3 h-6 w-6 text-navy-600" />
              Career Path Strategy
            </CardTitle>
            <CardDescription>
              Strategic roadmap for your career progression
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {advisoryData.path_strategy.map((strategy, index) => (
                <div
                  key={index}
                  className="p-4 border border-slate-200 rounded-lg"
                >
                  <div className="flex items-start justify-between mb-3">
                    <h4 className="font-semibold text-slate-800">
                      {strategy.title}
                    </h4>
                    <div className="flex items-center space-x-2">
                      <Badge
                        variant="outline"
                        className={getPriorityColor(strategy.priority)}
                      >
                        {strategy.priority} Priority
                      </Badge>
                      <Badge
                        variant="outline"
                        className="bg-purple-100 text-purple-800 border-purple-300"
                      >
                        <Clock className="w-3 h-3 mr-1" />
                        {strategy.timeframe}
                      </Badge>
                    </div>
                  </div>
                  <p className="text-sm text-slate-600">
                    <strong>Next Action:</strong> {strategy.next_action}
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Call to Action */}
        <Card className="bg-gradient-to-r from-green-50 to-blue-50 border-green-200">
          <CardContent className="text-center py-8">
            <Award className="w-12 h-12 text-green-600 mx-auto mb-4" />
            <h3 className="text-xl font-semibold text-green-800 mb-2">
              Ready to Accelerate Your Career?
            </h3>
            <p className="text-green-700 mb-4">
              Get personalized 1-on-1 guidance from our career experts to
              fast-track your progress.
            </p>
            <Button
              onClick={() => setShowConsultationModal(true)}
              className="bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800 text-white"
            >
              <Globe className="mr-2 h-4 w-4" />
              Schedule Expert Consultation
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Consultation Modal */}
      <ConsultationModal
        isOpen={showConsultationModal}
        onClose={() => setShowConsultationModal(false)}
      />
    </div>
  );
};

export default AdvisoryReport;
