// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uevcuyuppopmspmdrbpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVldmN1eXVwcG9wbXNwbWRyYnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTc1MTMsImV4cCI6MjA2NzUzMzUxM30.kMDa4riwJmXO92_AwZe_v_r5GZnP9-foGR4uwCp0XSY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});